# SERVER
server.port=8080
server.servlet.context-path=/standard

spring.application.name=@project.artifactId@
application.name=@project.artifactId@
build.version=@project.version@
java.version=@java.version@
build.timestamp=@timestamp@

spring.banner.charset=UTF-8
spring.banner.location=classpath:banner.txt

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.deserialization.FAIL_ON_UNKNOWN_PROPERTIES=false
spring.jackson.deserialization.ACCEPT_SINGLE_VALUE_AS_ARRAY=true
spring.jackson.mapper.ACCEPT_CASE_INSENSITIVE_PROPERTIES=true
spring.jackson.defaultPropertyInclusion=NON_NULL

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

#ehcache
spring.cache.jcache.config=classpath:ehcache.xml

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/standard-app

#logging
logging.level.root=debug
logging.level.org.springframework.web=debug
logging.level.org.hibernate=debug
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type=error

logging.level.org.springframework.security=TRACE
