# SERVER
server.port=8080


application.name=@project.artifactId@
build.version=@project.version@
java.version=@java.version@
build.timestamp=@timestamp@

spring.banner.charset=UTF-8
spring.banner.location=classpath:banner.txt

#Data Source
spring.datasource.url=jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driverClassName=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=console

spring.jpa.show-sql=true
spring.jpa.hibernate.use-new-id-generator-mappings=false
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.javax.persistence.sharedCache.mode=ALL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.deserialization.FAIL_ON_UNKNOWN_PROPERTIES=false
spring.jackson.deserialization.ACCEPT_SINGLE_VALUE_AS_ARRAY=true
spring.jackson.mapper.ACCEPT_CASE_INSENSITIVE_PROPERTIES=true
spring.jackson.defaultPropertyInclusion=NON_NULL


#ehcache
spring.cache.jcache.config=classpath:ehcache.xml

#liquibase
spring.liquibase.enabled=false

#logging
logging.level.root=debug
logging.level.org.springframework.web=error
logging.level.org.hibernate=debug
logging.level.org.hibernate.SQL=error
logging.level.org.hibernate.type=error
