version: 2.1
executors:
  maven-executor:
    docker:
      - image: cimg/openjdk:21.0  # Specify the desired JDK version here
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m  # Customize the JVM maximum heap limit

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run:
          name: Maven Clean Install
          command: mvn clean install

      - run:
          name: Maven Dependency Go Offline
          command: mvn dependency:go-offline

      - run:
          name: Run Tests
          command: mvn test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Save Test Results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

      - store_test_results:
          path: ~/test-results
