version: 2.1
executors:
  default-executor:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m

jobs:
  build:
    executor: default-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn clean install
      - run: mvn dependency:go-offline
      - run: mvn test
      - run:
          name: SonarQube Analysis
          command: |
            ./mvnw sonar:sonar \  
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \  
              -Dsonar.host.url=$SONAR_HOST_URL \  
              -Dsonar.login=$SONAR_TOKEN
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
