create table withdrawal
(
    id                 bigint generated by default as identity,
    created_by         bigint,
    creation_date      date,
    creation_time      time,
    last_modified_by   bigint,
    last_modified_date timestamp,
    version            bigint,
    amount             double       not null,
    description        varchar(255) not null,
    pos                bigint       not null,
    primary key (id)
);

create table brand
(
    id                 bigint generated by default as identity,
    created_by         bigint,
    creation_date      date,
    creation_time      time,
    last_modified_by   bigint,
    last_modified_date timestamp,
    version            bigint,
    description        varchar(45) not null,
    name               varchar(45) not null,
    status             varchar(255),
    primary key (id)
);

create table category
(
    id                 bigint generated by default as identity,
    created_by         bigint,
    creation_date      date,
    creation_time      time,
    last_modified_by   bigint,
    last_modified_date timestamp,
    version            bigint,
    description        varchar(45),
    name               varchar(45) not null,
    status             varchar(255),
    primary key (id)
);

create table category_has_subcategory
(
    category_id    bigint not null,
    subcategory_id bigint not null,
    primary key (category_id, subcategory_id)
);

create table customer
(
    id                 bigint generated by default as identity,
    created_by         bigint,
    creation_date      date,
    creation_time      time,
    last_modified_by   bigint,
    last_modified_date timestamp,
    version            bigint,
    api_key            varchar(45),
    customer_name      varchar(255),
    primary key (id)
);

create table domain
(
    id                 bigint generated by default as identity,
    created_by         bigint,
    creation_date      date,
    creation_time      time,
    last_modified_by   bigint,
    last_modified_date timestamp,
    version            bigint,
    description        varchar(45) not null,
    name               varchar(45) not null,
    status             varchar(255),
    primary key (id)
);

create table items_type_measure
(
    id                 bigint generated by default as identity,
    created_by         bigint,
    creation_date      date,
    creation_time      time,
    last_modified_by   bigint,
    last_modified_date timestamp,
    version            bigint,
    amount             varchar(255),
    brand_id           bigint,
    category_id        bigint,
    measure_id         bigint,
    subcategory_id     bigint,
    primary key (id)
);

create table measure
(
    id                 bigint generated by default as identity,
    created_by         bigint,
    creation_date      date,
    creation_time      time,
    last_modified_by   bigint,
    last_modified_date timestamp,
    version            bigint,
    description        varchar(45) not null,
    name               varchar(45) not null,
    status             varchar(255),
    primary key (id)
);

create table `order`
(
    id                   bigint generated by default as identity,
    created_by           bigint,
    creation_date        date,
    creation_time        time,
    last_modified_by     bigint,
    last_modified_date   timestamp,
    version              bigint,
    changing               double,
    discount             double,
    paid_amount          double,
    payment              double,
    pending_amount       double,
    quantity             integer not null,
    status               varchar(255),
    sub_total            double,
    total_amount         double,
    total_amount_to_paid double,
    customer_id          bigint  not null,
    payment_method_id    bigint  not null,
    pos_id               bigint  not null,
    primary key (id)
);

create table order_has_item_product
(
    id                                      bigint generated by default as identity,
    created_by                              bigint,
    creation_date                           date,
    creation_time                           time,
    last_modified_by                        bigint,
    last_modified_date                      timestamp,
    version                                 bigint,
    quantity                                integer,
    unit_value                              double,
    order_id                                bigint,
    product_has_items_items_type_measure_id bigint,
    primary key (id)
);

create table payback
(
    id                 bigint generated by default as identity,
    created_by         bigint,
    creation_date      date,
    creation_time      time,
    last_modified_by   bigint,
    last_modified_date timestamp,
    version            bigint,
    amount             double,
    description        varchar(255),
    name               varchar(255),
    customer_id        bigint,
    pos_id             bigint,
    primary key (id)
);

create table payment_method
(
    id                 bigint generated by default as identity,
    created_by         bigint,
    creation_date      date,
    creation_time      time,
    last_modified_by   bigint,
    last_modified_date timestamp,
    version            bigint,
    description        varchar(45) not null,
    discount_percent   integer     not null check (discount_percent <= 100 AND discount_percent >= 0),
    name               varchar(45) not null,
    status             varchar(255),
    primary key (id)
);

create table pos
(
    id                 bigint generated by default as identity,
    created_by         bigint,
    creation_date      date,
    creation_time      time,
    last_modified_by   bigint,
    last_modified_date timestamp,
    version            bigint,
    amount_final       double default 0,
    close_date         date,
    close_time         time,
    open_amount        double default 0 not null,
    open_date          date             not null,
    open_time          time             not null,
    status             varchar(255),
    total              double default 0,
    total_discount     double default 0,
    total_sales       double default 0,
    primary key (id)
);

create table product
(
    id                 bigint generated by default as identity,
    created_by         bigint,
    creation_date      date,
    creation_time      time,
    last_modified_by   bigint,
    last_modified_date timestamp,
    version            bigint,
    bar_code           varchar(255) not null,
    cost_price         double       not null,
    description        varchar(45)  not null,
    discount           double       not null,
    discount_percent   integer      not null check (discount_percent <= 100 AND discount_percent >= 0),
    discount_price     double       not null,
    name               varchar(45)  not null,
    percent            integer      not null check (percent <= 100 AND percent >= 0),
    photo              BLOB,
    price              double,
    sale_price         double       not null,
    status             varchar(255) not null,
    weight             double       not null,
    brand_id           bigint       not null,
    category_id        bigint       not null,
    measure_id         bigint       not null,
    provider_id        bigint       not null,
    subcategory_id     bigint       not null,
    primary key (id)
);

create table product_has_items_type_measure
(
    id                    bigint generated by default as identity,
    created_by            bigint,
    creation_date         date,
    creation_time         time,
    last_modified_by      bigint,
    last_modified_date    timestamp,
    version               bigint,
    quantity              integer,
    unit_value            double,
    items_type_measure_id bigint,
    product_id            bigint,
    primary key (id)
);

create table product_has_items_type_measure_has_domain
(
    product_has_items_type_measure_id bigint not null,
    domain_id                         bigint not null,
    primary key (product_has_items_type_measure_id, domain_id)
);


create table provider
(
    id                 bigint generated by default as identity,
    created_by         bigint,
    creation_date      date,
    creation_time      time,
    last_modified_by   bigint,
    last_modified_date timestamp,
    version            bigint,
    description        varchar(45) not null,
    name               varchar(45) not null,
    status             varchar(255),
    primary key (id)
);

create table subcategory
(
    id                 bigint generated by default as identity,
    created_by         bigint,
    creation_date      date,
    creation_time      time,
    last_modified_by   bigint,
    last_modified_date timestamp,
    version            bigint,
    description        varchar(45) not null,
    name               varchar(45) not null,
    status             varchar(255),
    primary key (id)
);
